### ISSUE TITLE
William Du Review Ticket

### ISSUE THREAD

**Issue by WilliamDu22** [WilliamDu22/WilliamDuRepository#1]
- [x] [GitHub page for Test Prep study, requiring 5.1, 5.2 notes and actions](https://github.com/WilliamDu22/WilliamDuRepository/wiki/5.1-5.2-Notes)

- [x] [GitHub page that documents Data Structures project, using code snippets for key learnings, and links to  GitHub for code and Replit for runtime](https://replit.com/@WilliamDu6/CSP#main.py)

- [x] [GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime](https://github.com/NoahJ214/Team-Aaiaa-Project-Tri-2/wiki/William-Du-Evaluation-of-Create-Task-Project)

**Comment by nicm2** [comment]
Individual GitHub pages (3 points)

- GitHub page for Test Prep study, requiring 5.1, 5.2 notes and actions (1/1) - Github page has all required notes and actions for 5.1, 5.2 

- GitHub page that documents Data Structures project, using code snippets for key learnings, and links to  GitHub for code and Replit for runtime (1/1) - Github page that documents Data Structures with link to Replit showing code and challenges work

- GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime (1/1) - Github page with Create task organized showing runtime and pictures
