### ISSUE TITLE
William Du - Lists and Loops Review Ticket 

### ISSUE THREAD

**Issue by WilliamDu22** [WilliamDu22/WilliamDuRepository#2]
- [x] [GitHub page for Test Prep study, requiring 5.3, 5.4 notes and actions( See "GitHub pages actions" at the bottom of each TPT page on cspcoders).](https://williamdu22.github.io/WilliamDuRepository/notes)

- [x] [GitHub page that documents key learnings and code snippets using GitHub and Replit.
InfoDB lists
InfoDB loops
Fibonacci - (For Fibonacci(n)  print complete list 0 - n  and not just the nth term)](https://replit.com/@WilliamDu6/CSP#main.py)

**Comment by nicm2** [comment]
Crossover Grade-
- Github Page w/ TPT 5.3, 5.4 notes and actions - Page with descriptive and detailed notes, complete with both 5.3, 5.4 and the github actions for this week (1/1)
- Github Page with Replit embed and link documenting learning, Replit and github code with InfoDB lists and loops running and Fibonacci project (2/2)

Total: 3/3
