### ISSUE TITLE
Week 2 Classy Functions - William Du

### ISSUE THREAD

**Issue by WilliamDu22** [WilliamDu22/WilliamDuRepository#4]
- [ ] GitHub page that documents key learnings and code snippets using GitHub and replit (See Challenges at the bottom of TT2
- [x] [Organize files, directories and menus for the first 3 weeks.](https://williamdu22.github.io/WilliamDuRepository/datastructure)
- [x] [Write Factorial function using classes, providing implementation of call.](https://williamdu22.github.io/WilliamDuRepository/datastructure)
- [x] [Select your own Math function. Write it in Imperative and OOP form.](https://williamdu22.github.io/WilliamDuRepository/datastructure)
- [x] Extra Credit. [Write Palindrome function using classes, must provide implementation of call. Must indicate where error - [x] occurs on front and back comparison.](https://williamdu22.github.io/WilliamDuRepository/datastructure)

3/3 points

**Comment by nicm2** [comment]
Crossover Grading:

- GitHub page that documents key learnings and code snippets using GitHub and replit (See Challenges at the bottom of  [TT2 (Links to an external site.)](https://github.com/nighthawkcoders/nighthawk_csp/wiki/Tri-3-TT2-Python-Classes) for details)
- Organize files, directories and menus for the first 3 weeks. 
- Write Factorial function using classes, providing implementation of call.
- Select your own Math function. Write it in Imperative and OOP form. 
- Extra Credit.  Write Palindrome function using classes, must provide implementation of call.  Must indicate where error occurs on front and back comparison.

Individual Grade: 3.75/3  - +1 extra credit from palindrome, working math function using imperative and oop, files organized in directories based on topics, factorial function using class and call working, -.25 for weak page documenting key learnings (oop, functions) using snippets. CB notes is organized and all there with Github actions. Work is organized and easy to see.

Group Crossover Team Grade: 2/2

Total: 5.75/5 
Great Job!
