### ISSUE TITLE
Algorithmic Final Review Ticket

### ISSUE THREAD

**Issue by WilliamDu22** [WilliamDu22/WilliamDuRepository#5]
TOTAL SCORE: 9.0

Individual Coding:
- [x] GitHub Pages showing key learnings and challenges conquered from Tech Talks
- [x] GitHub commits you have made, show GitHub insights into your code commits.
- [x] Show Code running on Replit as well as IntelliJ
- [x] Menu review illustrating use of Lists and navigation: show runtime, code organization, code and comments
- [x] List and Loops: show runtime, code organization, code and comments
- [x] Class review and understanding: show runtime, code organization, code and comments
- [x] Show Crossover contribution:  Highlight work you did in crossover project: show their Replit runtime, code commit(s) in their GitHub repo. Show anything you have done to enhance what you have learned from Python code

- [x] [Video 2 minutes: showing the above, quality suggested as follows](https://youtu.be/VAb14s970T8)

**Comment by danaylevy2004** [comment]
- [x] GitHub Pages showing key learnings -- Includes review tickets and things learned throughout the week
- [x] Github commits are shown 
- [x] Code runs well on both 
- [x] Menu has lists and navigation and shows what William learned from the previous weeks
- [x] Has lists and loops, but didn't show runtime of the lists and loops. Code is organized and contains comments
- [x] Demonstrated overall understanding
- [x] Shown crossover commits, but didn't really specify on what he has done to enhance his learning of Python code
Grand total: 9/10
- [x]
