### ISSUE TITLE
Accounts and Logins

### ISSUE THREAD

**Issue by WilliamDu22** [WilliamDu22/WilliamDuRepository#6]
**4.5/5**

**Individual**
[CB Create Task Coding requirements documented](https://github.com/WilliamDu22/WilliamDuRepository/wiki/CB-Create-Task-Coding-requirements) 1 Point

[Runtime of Code(with comments) on Replit/Intelli](https://github.com/WilliamDu22/WilliamDuRepository/blob/main/CB%20Create%20Task/Sports%20Roster.html) 1 Point

**Group**
[Hack #1 Add Phone Number to Sign Up / Authorization screen
](https://github.com/Ethan-Gravin25/TLDEW/blob/main/presentation.md) 1 Point
[Hack #2 Add logout to CRUD screen
](https://github.com/Ethan-Gravin25/TLDEW/blob/main/presentation.md) 1 Point
[Hack #3 Add login_required to another portion of the project](https://github.com/Ethan-Gravin25/TLDEW/blob/main/presentation.md) 1 Point

**Comment by nicm2** [comment]
CB Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. (2 Points - Individual)

CB Create Task Coding requirements documented 1/1

Runtime of Code(with comments) on Replit/Intellij 0.75/1

 Accounts and Logins Challenges/Hacks ( 3 Points - Pair/Trio)

Hack 1 Add Phone Number to Sign Up / Authorization screen 1/1

Hack 2 Add logout to CRUD screen 1/1

Hack 3 Add login_required to another portion of the project 1/1

Overall the Create task project was documented in the github individual page well and included runtime to the replit project. I took off 0.25 points for a lack of comments on the project which made understanding what was going on a lot harder. The login feature was also included in the group project with all the hacks. No extra cred. 
Total: 4.75/5
