### ISSUE TITLE
Proctored MCQ Week1 - William Du

### ISSUE THREAD

**Issue by WilliamDu22** [WilliamDu22/WilliamDuRepository#8]
Score 5/5 Peer Score by Zach Ye

- [x] [Start review ticket with study plan and study reflection for week, due EOD Monday 4/18](https://github.com/WilliamDu22/WilliamDuRepository/issues/7) 1/1
- [x] [Finals-Quiz1 score/50 and corrections](https://williamdu22.github.io/WilliamDuRepository/notes/FinalsQuiz.md) 1/1
- [x] [Finals-Quiz2 score/50 and corrections](https://williamdu22.github.io/WilliamDuRepository/notes/FinalsQuiz.md) 1/1
- [x] [Create Task code/runtime and 1 min video are reviewed by another person, you may request Teacher review as time permits Review ticket with Crossover Score on Monday 4/25 in class](https://youtu.be/AwGULiv1zX4) 1/1
- [x] [GitHub Page](https://williamdu22.github.io/WilliamDuRepository/) 1/1

**Comment by zachye111** [comment]
5/5
- Study plan is complete and concise 1/1
- The finals quiz is complete above 50 percent with corrections 1/1
- The second finals quiz is complete above 50 percent with corrections 1/1
- The create task is complete with working runtime. The video is also under 1 minute. 1/1
- Review Ticket from 4/25 is complete with score. 1/1
