### ISSUE TITLE
Week 6 Quiz3 and Create Task Review

### ISSUE THREAD

**Issue by WilliamDu22** [WilliamDu22/WilliamDuRepository#9]
TOTAL: 4.5/5
Reviewed by Lucas Ho

- [x] [GH Indi Page, Review Ticket, Crossover graded, Study Plan](https://github.com/WilliamDu22/WilliamDuRepository/issues/7)
- [x] Create Task and Create Task Crossover Review comments (completed by Thu)
- [x] [Quiz3 MCQ results and test corrections](https://williamdu22.github.io/WilliamDuRepository/testcorrections)

**Comment by lucasho22** [comment]
Reviewed by Lucas Ho
4.5/5

GH Individual pages are organized and complete. Very easy to navigate things. Review ticket done and study plan shows a good plan of preparing for the AP test. 
Create Task is completed and shows understanding of terms. Video is nice. Maybe work on making it look a little nicer.
Quiz 3 corrections and results done. Shows an understanding of why the questions answered were wrong.
